# Generated by Django 6.0 on 2025-12-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name = 'StudentInfo',
            new_name = 'StudentModel'
        )
    ]
